import 'package:flutter/material.dart';
import 'app_models.dart';

List<ModuleData> buildModules() {
  return [
    ModuleData(
      number: 1,
      color: const Color(0xFF2E7D32),
      icon: Icons.health_and_safety_rounded,
      homeIconAsset: 'assets/images/home_icons/home_1.jpg',
      title: const LocalizedText('Stoma Basics', 'स्टोमा की बुनियादी जानकारी'),
      subtitle: const LocalizedText(
        'Learn the basics of ostomy care and understanding.',
        'ओस्टॉमी और उसकी देखभाल की बुनियादी जानकारी सीखें।',
      ),
      overview: const LocalizedText(
        'This module explains what an ostomy is, its types, normal stoma appearance, expected early changes and what output to expect.',
        'इस मॉड्यूल में बताया गया है कि ओस्टॉमी क्या है, उसके प्रकार क्या हैं, स्टोमा सामान्य रूप से कैसा दिखता है और शुरुआती दिनों में क्या बदलाव हो सकते हैं।',
      ),
      imageAsset: 'assets/images/module_1.jpg',
      cardImageAlignment: const Alignment(-0.75, -0.55),
      headerImageAlignment: const Alignment(-0.9, -0.72),
      lessonImageAlignment: const Alignment(0.55, -0.72),
      lessons: const [],
    ),
    ModuleData(
      number: 2,
      color: const Color(0xFF2E7D32),
      icon: Icons.medical_services_rounded,
      homeIconAsset: 'assets/images/home_icons/home_2.jpg',
      title: const LocalizedText('Stoma Care Kit', 'स्टोमा केयर किट'),
      subtitle: const LocalizedText(
        'Learn about the essential items for daily stoma care.',
        'रोज़ की स्टोमा देखभाल के लिए ज़रूरी सामान जानें।',
      ),
      overview: const LocalizedText(
        'This module introduces the pouch system, skin protection items, cutting tools, cleaning materials and quick care tips.',
        'इस मॉड्यूल में पाउच सिस्टम, त्वचा की सुरक्षा वाली वस्तुएं, काटने के उपकरण, सफाई सामग्री और देखभाल के सुझाव दिए गए हैं।',
      ),
      imageAsset: 'assets/images/module_2.jpg',
      cardImageAlignment: const Alignment(-0.7, -0.7),
      headerImageAlignment: const Alignment(-0.9, -0.78),
      lessonImageAlignment: const Alignment(0.55, -0.78),
      lessons: const [],
    ),
    ModuleData(
      number: 3,
      color: const Color(0xFF1565C0),
      icon: Icons.fact_check_rounded,
      homeIconAsset: 'assets/images/home_icons/home_3.jpg',
      title: const LocalizedText(
        'Stoma Care Procedure',
        'स्टोमा देखभाल प्रक्रिया',
      ),
      subtitle: const LocalizedText(
        'Follow the step-by-step process for safe stoma care at home.',
        'घर पर सुरक्षित स्टोमा देखभाल के लिए चरण-दर-चरण प्रक्रिया अपनाएं।',
      ),
      overview: const LocalizedText(
        'This module gives the daily procedure from removing the old pouch to cleaning, measuring, sealing, emptying and disposal.',
        'इस मॉड्यूल में पुराना पाउच हटाने से लेकर सफाई, माप, सीलिंग, खाली करना और निपटान तक की पूरी प्रक्रिया दी गई है।',
      ),
      imageAsset: 'assets/images/module_3.jpg',
      cardImageAlignment: const Alignment(-0.78, -0.72),
      headerImageAlignment: const Alignment(-0.9, -0.82),
      lessonImageAlignment: const Alignment(0.55, -0.8),
      lessons: const [],
    ),
    ModuleData(
      number: 4,
      color: const Color(0xFF2E7D32),
      icon: Icons.restaurant_rounded,
      homeIconAsset: 'assets/images/home_icons/home_4.jpg',
      title: const LocalizedText('Diet & Fluids', 'आहार और तरल'),
      subtitle: const LocalizedText(
        'Choose foods and fluids that help you stay comfortable.',
        'ऐसे भोजन और तरल चुनें जो आपको आरामदायक रखें।',
      ),
      overview: const LocalizedText(
        'This module explains recovery diet, hydration, stool-thickening foods, foods to limit and warning signs that need nurse support.',
        'इस मॉड्यूल में रिकवरी डाइट, पानी की मात्रा, मल को गाढ़ा करने वाले खाद्य पदार्थ, किन चीजों से बचना है और कब नर्स से संपर्क करना है, यह बताया गया है।',
      ),
      imageAsset: 'assets/images/module_4.jpg',
      cardImageAlignment: const Alignment(-0.74, -0.74),
      headerImageAlignment: const Alignment(-0.9, -0.82),
      lessonImageAlignment: const Alignment(0.62, -0.8),
      lessons: const [],
    ),
    ModuleData(
      number: 5,
      color: const Color(0xFF2E7D32),
      icon: Icons.directions_walk_rounded,
      homeIconAsset: 'assets/images/home_icons/home_5.jpg',
      title: const LocalizedText('Recovery Exercises', 'रिकवरी एक्सरसाइज़'),
      subtitle: const LocalizedText(
        'Safe movement and exercises for a smoother recovery.',
        'सुरक्षित गतिविधि और व्यायाम से बेहतर रिकवरी करें।',
      ),
      overview: const LocalizedText(
        'This module covers early walking, gentle abdominal exercises, hernia prevention and safe activity progression after surgery.',
        'इस मॉड्यूल में शुरुआती चलना, हल्के पेट के व्यायाम, हर्निया से बचाव और सर्जरी के बाद सुरक्षित गतिविधि बढ़ाने की जानकारी है।',
      ),
      imageAsset: 'assets/images/module_5.jpg',
      cardImageAlignment: const Alignment(-0.72, -0.72),
      headerImageAlignment: const Alignment(-0.9, -0.8),
      lessonImageAlignment: const Alignment(0.62, -0.8),
      lessons: const [],
    ),
    ModuleData(
      number: 6,
      color: const Color(0xFF2E7D32),
      icon: Icons.tips_and_updates_rounded,
      homeIconAsset: 'assets/images/home_icons/home_6.jpg',
      title: const LocalizedText('Everyday Tips', 'रोज़मर्रा के सुझाव'),
      subtitle: const LocalizedText(
        'Travel, clothing, work and daily confidence with a stoma.',
        'स्टोमा के साथ यात्रा, कपड़े, काम और रोज़मर्रा के आत्मविश्वास के सुझाव।',
      ),
      overview: const LocalizedText(
        'This module helps you manage travel, public restrooms, safety, relationships, clothing and return to work.',
        'यह मॉड्यूल यात्रा, सार्वजनिक शौचालय, सुरक्षा, रिश्ते, कपड़े और काम पर वापसी को संभालने में मदद करता है।',
      ),
      imageAsset: 'assets/images/module_6.jpg',
      cardImageAlignment: const Alignment(-0.85, -0.86),
      headerImageAlignment: const Alignment(-0.95, -0.96),
      lessonImageAlignment: const Alignment(0.7, -0.94),
      lessons: const [],
    ),
    ModuleData(
      number: 7,
      color: const Color(0xFFE53935),
      icon: Icons.warning_amber_rounded,
      homeIconAsset: 'assets/images/home_icons/home_7.jpg',
      title: const LocalizedText('Warning Signs', 'चेतावनी संकेत'),
      subtitle: const LocalizedText(
        'Recognize early danger signs and seek help quickly.',
        'खतरे के शुरुआती संकेत पहचानें और समय पर सहायता लें।',
      ),
      overview: const LocalizedText(
        'This module covers stoma color changes, output problems, dehydration, infection, pain and emergency signs that need immediate action.',
        'इस मॉड्यूल में स्टोमा के रंग में बदलाव, आउटपुट की समस्या, डिहाइड्रेशन, संक्रमण, दर्द और आपात संकेत शामिल हैं जिनमें तुरंत कार्रवाई ज़रूरी है।',
      ),
      imageAsset: 'assets/images/module7_patient.png',
      cardImageAlignment: const Alignment(-0.82, -0.82),
      headerImageAlignment: const Alignment(-0.92, -0.95),
      lessonImageAlignment: const Alignment(0.68, -0.92),
      lessons: const [],
    ),
    ModuleData(
      number: 8,
      color: const Color(0xFF1565C0),
      icon: Icons.local_hospital_rounded,
      homeIconAsset: 'assets/images/home_icons/home_8.jpg',
      title: const LocalizedText('Quick Care Tips', 'त्वरित देखभाल सुझाव'),
      subtitle: const LocalizedText(
        'Essential tips for daily stoma care and comfort.',
        'दैनिक स्टोमा देखभाल और आराम के लिए आवश्यक सुझाव।',
      ),
      overview: const LocalizedText(
        'Quick tips and reminders for daily stoma care management.',
        'दैनिक स्टोमा देखभाल प्रबंधन के लिए त्वरित सुझाव और याद दिलाने।',
      ),
      imageAsset: 'assets/images/module_8.jpg',
      cardImageAlignment: const Alignment(-0.82, -0.82),
      headerImageAlignment: const Alignment(-0.92, -0.95),
      lessonImageAlignment: const Alignment(0.68, -0.92),
      lessons: const [],
    ),
  ];
}
